[package]
name = "kbdmshook"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.17.1"
anyhow = "1"
num_enum = "0.5.11"

[dependencies.windows]
version = "0.43.0"
features = [
    "Win32_UI_WindowsAndMessaging",
    "Win32_Foundation",
]